version: '3.5'

services:

  backend:
    build: 
      context: ./backend
      dockerfile: prod.Dockerfile
    restart: always
    command: bash -c "./wait-for-it.sh ${MYSQL_HOST}:${MYSQL_PORT} -- npm run start"

  nginx:
    ports:
      - 80:80
