version: "3"

services:

  db:
    image: mysql
    networks: 
      - webnet
    volumes:
      - db-volume:/var/lib/mysql:rw
    restart: always
    env_file:
      - ./dev.env
    
  redis:
    image: redis
    networks:
      - webnet
    restart: always
    volumes:
      - redis-volume:/data
    env_file:
      - ./dev.env

  backend:
    build: ./backend
    networks:
      - webnet
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    env_file:
      - ./dev.env
    depends_on:
      - db
      - redis
    command: 
      bash -c "chmod 755 / && chmod 755 . -R 
      && ./wait-for-it.sh $${MYSQL_HOST}:$${MYSQL_PORT} -- npm run start:watch-docker"
  
  nginx:
    build: ./nginx
    networks:
      - webnet
    restart: always
    ports:
    - "8000:80"
    depends_on:
      - backend
    env_file:
      - ./dev.env
    
networks:

  webnet:

volumes:

  db-volume:
  redis-volume: