version: '3.5'

services:

  db:
    image: mysql
    networks: 
      - webnet
    volumes:
      - db-volume:/var/lib/mysql:rw
    restart: always
    env_file:
      - ./.env

  redis:
    image: redis
    networks:
      - webnet
    restart: always
    env_file:
      - ./.env
    volumes:
      - redis-volume:/data

  backend:
    build: ./backend
    restart: always
    networks:
      - webnet
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    networks:
      - webnet
    volumes:
      - ./backend/public:/public
    restart: always
    env_file:
      - ./.env
    depends_on:
      - backend
    ports:
      - 80:80

networks:

  webnet:

volumes:

  db-volume:
  redis-volume:
