version: "3"

services:

  db:
    image: mysql
    networks: 
      - webnet
    volumes:
      - db-volume:/var/lib/mysql:rw
    restart: always
    env_file:
      - ./.env
  redis:
    image: redis
    networks:
      - webnet
    restart: always
    env_file:
      - ./.env
    volumes:
      - redis-volume:/data
  backend:
    build: ./backend
    networks:
      - webnet
    volumes:
      - ./backend:/backend
      - static-volume:/backend/public
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    command: 
      bash -c "chmod 755 / && chmod 755 . -R 
      && ./wait-for-it.sh ${MYSQL_HOST}:${MYSQL_PORT} -- npm run start:watch-docker"
  nginx:
    build: ./nginx
    networks:
      - webnet
    volumes:
      - static-volume:/backend/public
    restart: always
    env_file:
      - ./.env
    ports:
    - "8000:80"
    depends_on:
      - backend
networks:

  webnet:

volumes:

  static-volume:
  db-volume:
  redis-volume: